### ISSUE TITLE
_ is not defined and browseriy

### ISSUE THREAD

**Issue by fernoftheandes** [cabrel/angular-lodash#14]
Hi,

I am getting the dreadful _ is not defined in the file generated by `browserify`, even though I require the proper libs in the right sequence in the source js file, like such:

```
require('../../bower_components/angular/angular.js');
require('../../bower_components/lodash/dist/lodash.compat.js');
require('../../bower_components/angular-lodash/angular-lodash.js');
```

Any thoughts?
Thanks!

**Comment by felixfbecker** [comment]
if you're using browserify, why not simply do `var _  = require('lodash')`? I dont think this has something to do with angular-lodash

**Comment by fernoftheandes** [comment]
Thanks. I will give this a try and re-open the issue if it does not work.
