### ISSUE TITLE
Using filter like exmaple in readme gives error;

### ISSUE THREAD

**Issue by syzer** [cabrel/angular-lodash#3]
Used example from readme got angular error;

this one:
[stackoverflow](http://stackoverflow.com/questions/17116114/how-to-troubleshoot-angular-10-digest-iterations-reached-error)

**Comment by MasseGuillaume** [comment]
Shuffle is not determinism, it will return different values so digest will cycle 10 times, the limit. It's not the best example

**Comment by syzer** [comment]
true

**Comment by syzer** [comment]
:+1:
